# Generated by Django 5.2.12 on 2026-03-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='students_st_is_acti_c00e81_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['document_id'], name='students_st_documen_9d97ee_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='students_st_email_e271bc_idx'),
        ),
    ]
