# Generated by Django 5.2.12 on 2026-03-29 01:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_alter_certificate_event_and_more'),
        ('events', '0004_alter_enrollment_options_alter_event_options_and_more'),
        ('students', '0002_alter_student_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_at']},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student', 'event'], name='certificado_student_098aff_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_active'], name='certificado_is_acti_5708ca_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['category'], name='certificado_categor_10359f_idx'),
        ),
    ]
