# Generated by Django 5.2.12 on 2026-03-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['full_name'], 'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['is_active'], name='instructors_is_acti_a5a7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['email'], name='instructors_email_b143f5_idx'),
        ),
    ]
