# Generated by Django 5.2.12 on 2026-03-29 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0005_alter_certificate_options_alter_template_options_and_more'),
        ('deliveries', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverylog',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='certificados.certificate'),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['status'], name='deliveries__status_d84956_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['delivery_method'], name='deliveries__deliver_961d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['certificate'], name='deliveries__certifi_f3909a_idx'),
        ),
    ]
